Make rails 6 compatible
programmable-banking-community/investec_open_api pull request #8
Opened 2022-01-26 11:47 UTC by DrJamesCoates

Updated certain files to reflect up to date practices and newer versions of dependencies to get the specs to pass and to make the Investec Open API gem compatible with Rails 6.

2022-01-26 14:10 UTC, jethroflanagan approved these changes
Looks good, thanks.

2022-01-26 14:10 UTC, jethroflanagan commented on spec/lib/investec_open_api/client_spec.rb
> +          "Authorization" => "Basic VGVzdDpTZWNyZXQ=",
We checked to see that this was just the above username and pass 👍

2022-01-26 14:20 UTC, MarkusKuhn approved these changes
Thanks so much for the contribution James!
I only have two small comments on the pull request, but otherwise it looks great!
Thanks for taking the time to make the gem up to date with conventions and making it compatible with Rails 6!

2022-01-26 14:20 UTC, MarkusKuhn commented on spec/lib/investec_open_api/client_spec.rb
> +    #WebMock.allow_net_connect!(allow_localhost: true)
Since stubs are being made in the spec, including the before block here, could we remove this?

2022-01-26 14:20 UTC, MarkusKuhn commented on spec/spec_helper.rb
> +#WebMock.allow_net_connect!(allow_localhost: true)
If this isn't being used at the moment, could we remove it?

2022-01-26 15:11 UTC, DrJamesCoates commented
Hi Markus and Jethro!

Thank you so much for the feedback! I've made the changes you requested to
the pull request, as well as one other small change to client_spec.

Let me know if you'd like me to change / update anything else!

Have a lovely evening!

James

On Wed, 26 Jan 2022, 4:20 PM Markus Kuhn, ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Thanks so much for the contribution James!
> I only have two small comments on the pull request, but otherwise it looks
> great!
> Thanks for taking the time to make the gem up to date with conventions and
> making it compatible with Rails 6!
> ------------------------------
>
> In spec/lib/investec_open_api/client_spec.rb
> <https://github.com/offerzen/investec_open_api/pull/8#discussion_r792676297>
> :
>
> > @@ -7,6 +7,9 @@
>    let(:client) { InvestecOpenApi::Client.new }
>
>    before do
> +
> +    #WebMock.allow_net_connect!(allow_localhost: true)
>
> Since stubs are being made in the spec, including the before block here,
> could we remove this?
> ------------------------------
>
> In spec/spec_helper.rb
> <https://github.com/offerzen/investec_open_api/pull/8#discussion_r792677003>
> :
>
> > @@ -3,6 +3,8 @@
>  require "investec_open_api"
>  require 'webmock/rspec'
>
> +#WebMock.allow_net_connect!(allow_localhost: true)
>
> If this isn't being used at the moment, could we remove it?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/offerzen/investec_open_api/pull/8#pullrequestreview-863593083>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATYQT57XNWDAFP6PILQASFDUX77JZANCNFSM5M22GDQA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-01-27 11:13 UTC, jethroflanagan commented
@DrJamesCoates thanks for making those changes. We're investigating the build pipeline failure, and will let you know if there is anything to change for it - or add in a fix from our side.

2022-02-15 09:36 UTC, jethroflanagan commented
@DrJamesCoates Apologies for the long delay on the investigation. The issue is that our CI pipeline also needs to have the correct Ruby and bundler versions.

Please change to the following in .travis.yml:
```yml
language: ruby
cache: bundler
rvm:
  - 3.0.2
before_install: gem install bundler -v 2.2.28
```
This just matches your existing specifications in `.ruby-version`

2022-02-15 09:37 UTC, jethroflanagan requested changes
@DrJamesCoates Apologies for the long delay on the investigation. The issue is that our CI pipeline also needs to have the correct Ruby and bundler versions.

Please change to the following in .travis.yml:
```yml
language: ruby
cache: bundler
rvm:
  - 3.0.2
before_install: gem install bundler -v 2.2.28
```
This just matches your existing specifications in `.ruby-version`

2023-05-05 05:48 UTC, closed without merging